import type { Metadata } from "next";
import {poppins} from "./fonts/fonts"
import "./globals.css";
import Navigation from "@/components/navigation/navigation";

export const metadata: Metadata = {
  title: "Kalaa Iris",
  description: "Generated by create next app",
  icons: [{url: "/fav-icon.png", sizes: "any", type: 'image/png'}]
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body
        className={`${poppins.variable} antialiased bg-black text-white`}
      >
        <main className="w-full max-w-[1980px] mx-auto border-x border-secondaryColor min-h-[200vh] relative">
          <Navigation />
          {children}
       </main>
      </body>
    </html>
  );
}
