import type { Metadata } from "next";
import {poppins} from "./fonts/fonts"
import "./globals.css";
import Navigation from "@/components/navigation/navigation";
import MobileNav from "@/components/mobileNav/MobileNav";
import FooterBar from "@/components/footer/footer";
import StaticLinkFooter from "@/components/staticLinkFooter.tsx/staticLinkFooter";
import FloatingWhatsApp from "@/components/floating-whatsapp/floating-whatsapp";
import { Toaster } from "@/components/ui/toaster"

export const metadata: Metadata = {
  title: "Kalaa Iris",
  description: "Generated by create next app",
  icons: [{url: "/fav-icon.png", sizes: "any", type: 'image/png'}],

  openGraph: {
    title: "Kalaa Iris",
    description: "WE CREATE ‘EYE’ CONIC ART",
    url: "https://kalaa-iris.vercel.app/",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body
        className={`${poppins.variable} antialiased bg-black text-white`}
      >
        <main className="w-full max-w-[1980px] mx-auto border-x border-hairlineColor min-h-[100vh] relative flex flex-col">
          <FloatingWhatsApp />
          <Toaster/>
          <Navigation />
          {children}
          <StaticLinkFooter />
          <FooterBar />
          <MobileNav /> 
       </main>
      </body>
    </html>
  );
}
